# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f1aa5cc56650384cadc3a9fcf17207ac87935fa3dd2a1def85696cbe19fd8b133dfab789f136b46396d82d351d731101680fed0f68923f65e8d64aec8f74a315

test:
  secret_key_base: 69f1e117de7fc287ac300825ef83d4c0c4bdf16af5ace3f46922dec525156770d239b8bb58b83139c083c5634984da0b6a32e4000eb120fabc4bb60ddbafe7c7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
